### ISSUE TITLE
Could this mod be compatible for gta underground?

### ISSUE THREAD

**Issue by ellie12134** [gennariarmando/v-hud#7]
I don't think there would much to do for compatibility for UG , just make the hud use the Game's own icons from gta3.img and don't use Map coloration

also as of right now the game crashes when pressing esc when in black screen after the cmd window opens and before the menu shows.
tho I don't know if it's caused by UG itself, since other people seem to have this issue

**Comment by gennariarmando** [comment]
New weapon icons can be added easily by adding the new icon inside the folder, and by adding a new entry inside the data file, no source code changes are needed.
About the radar map, internal world value needs to be increased and radar tiles must be added to the map folder in order to make them show correctly.
